//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FileManager.Resources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HelpConsole {
            get {
                return ResourceManager.GetString("HelpConsole", resourceCulture);
            }
        }
        
        internal static string HelpCommandExit {
            get {
                return ResourceManager.GetString("HelpCommandExit", resourceCulture);
            }
        }
        
        internal static string HelpCommandHelp {
            get {
                return ResourceManager.GetString("HelpCommandHelp", resourceCulture);
            }
        }
        
        internal static string HelpCommands {
            get {
                return ResourceManager.GetString("HelpCommands", resourceCulture);
            }
        }
        
        internal static string HelpCommandDrive {
            get {
                return ResourceManager.GetString("HelpCommandDrive", resourceCulture);
            }
        }
        
        internal static string HelpCommandChangeDirectory {
            get {
                return ResourceManager.GetString("HelpCommandChangeDirectory", resourceCulture);
            }
        }
        
        internal static string HelpCommandShowCurrentDirectory {
            get {
                return ResourceManager.GetString("HelpCommandShowCurrentDirectory", resourceCulture);
            }
        }
        
        internal static string HelpCommandShowDirectoryContents {
            get {
                return ResourceManager.GetString("HelpCommandShowDirectoryContents", resourceCulture);
            }
        }
        
        internal static string HelpCommandFind {
            get {
                return ResourceManager.GetString("HelpCommandFind", resourceCulture);
            }
        }
        
        internal static string HelpCommandShowFile {
            get {
                return ResourceManager.GetString("HelpCommandShowFile", resourceCulture);
            }
        }
        
        internal static string HelpCommandCopy {
            get {
                return ResourceManager.GetString("HelpCommandCopy", resourceCulture);
            }
        }
        
        internal static string HelpCommandMove {
            get {
                return ResourceManager.GetString("HelpCommandMove", resourceCulture);
            }
        }
        
        internal static string HelpCommandDelete {
            get {
                return ResourceManager.GetString("HelpCommandDelete", resourceCulture);
            }
        }
        
        internal static string HelpCommandCreateFile {
            get {
                return ResourceManager.GetString("HelpCommandCreateFile", resourceCulture);
            }
        }
        
        internal static string HelpCommandConcatenate {
            get {
                return ResourceManager.GetString("HelpCommandConcatenate", resourceCulture);
            }
        }
        
        internal static string HelpCommandDiff {
            get {
                return ResourceManager.GetString("HelpCommandDiff", resourceCulture);
            }
        }
    }
}
