//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FileManager.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MessageSplash {
            get {
                return ResourceManager.GetString("MessageSplash", resourceCulture);
            }
        }
        
        internal static string MessageManyAutoCompletionVariants {
            get {
                return ResourceManager.GetString("MessageManyAutoCompletionVariants", resourceCulture);
            }
        }
        
        internal static string ConsolePrompt {
            get {
                return ResourceManager.GetString("ConsolePrompt", resourceCulture);
            }
        }
        
        internal static string ErrorCommandNotFound {
            get {
                return ResourceManager.GetString("ErrorCommandNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        internal static string ErrorEncodingNotFound {
            get {
                return ResourceManager.GetString("ErrorEncodingNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorInvalidArgumentCount {
            get {
                return ResourceManager.GetString("ErrorInvalidArgumentCount", resourceCulture);
            }
        }
        
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        internal static string MessagePagerStop {
            get {
                return ResourceManager.GetString("MessagePagerStop", resourceCulture);
            }
        }
        
        internal static string MessageBinaryFile {
            get {
                return ResourceManager.GetString("MessageBinaryFile", resourceCulture);
            }
        }
        
        internal static string MessageRecursiveOperation {
            get {
                return ResourceManager.GetString("MessageRecursiveOperation", resourceCulture);
            }
        }
        
        internal static string MessageOverwriteFile {
            get {
                return ResourceManager.GetString("MessageOverwriteFile", resourceCulture);
            }
        }
        
        internal static string MessageDeleteFile {
            get {
                return ResourceManager.GetString("MessageDeleteFile", resourceCulture);
            }
        }
        
        internal static string ErrorNeedRecursive {
            get {
                return ResourceManager.GetString("ErrorNeedRecursive", resourceCulture);
            }
        }
        
        internal static string ErrorInvalidOptions {
            get {
                return ResourceManager.GetString("ErrorInvalidOptions", resourceCulture);
            }
        }
        
        internal static string ErrorDiffFirstLineNumber {
            get {
                return ResourceManager.GetString("ErrorDiffFirstLineNumber", resourceCulture);
            }
        }
        
        internal static string ErrorDiffSecondLineNumber {
            get {
                return ResourceManager.GetString("ErrorDiffSecondLineNumber", resourceCulture);
            }
        }
        
        internal static string ErrorDiffInvalidChangeType {
            get {
                return ResourceManager.GetString("ErrorDiffInvalidChangeType", resourceCulture);
            }
        }
        
        internal static string ErrorInvalidHelpString {
            get {
                return ResourceManager.GetString("ErrorInvalidHelpString", resourceCulture);
            }
        }
        
        internal static string ErrorDriveNotFound {
            get {
                return ResourceManager.GetString("ErrorDriveNotFound", resourceCulture);
            }
        }
        
        internal static string MessageOperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("MessageOperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        internal static string MessageDirectoryEnumeration {
            get {
                return ResourceManager.GetString("MessageDirectoryEnumeration", resourceCulture);
            }
        }
        
        internal static string ErrorInputOutput {
            get {
                return ResourceManager.GetString("ErrorInputOutput", resourceCulture);
            }
        }
        
        internal static string ErrorTooManyLines {
            get {
                return ResourceManager.GetString("ErrorTooManyLines", resourceCulture);
            }
        }
        
        internal static string ErrorFileTooBig {
            get {
                return ResourceManager.GetString("ErrorFileTooBig", resourceCulture);
            }
        }
        
        internal static string MessagePleaseWait {
            get {
                return ResourceManager.GetString("MessagePleaseWait", resourceCulture);
            }
        }
    }
}
